-- Clean up test data (CAUTION: This will delete ALL existing data)
-- Only run this in development! Comment out for production

-- Disable RLS temporarily for cleanup
ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE cv_embeddings DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_descriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE cache DISABLE ROW LEVEL SECURITY;
ALTER TABLE rate_limits DISABLE ROW LEVEL SECURITY;
ALTER TABLE approvals DISABLE ROW LEVEL SECURITY;
ALTER TABLE skill_gaps DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_metrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE llm_calls DISABLE ROW LEVEL SECURITY;
ALTER TABLE interview_questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE cover_letters DISABLE ROW LEVEL SECURITY;

-- Delete data from tables with foreign key dependencies (order matters!)
DELETE FROM messages;
DELETE FROM cv_embeddings;
DELETE FROM interview_questions;
DELETE FROM cover_letters;
DELETE FROM approvals;
DELETE FROM skill_gaps;
DELETE FROM tasks;
DELETE FROM job_descriptions;
DELETE FROM documents;
DELETE FROM sessions;
DELETE FROM user_metrics;
DELETE FROM llm_calls;
DELETE FROM cache;
DELETE FROM rate_limits;

-- Re-enable RLS
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE cv_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_descriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_gaps ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE llm_calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE interview_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE cover_letters ENABLE ROW LEVEL SECURITY;
